package com.nuvio.app.features.iptv

object QuickChannelList {
    val all: List<QuickChannel> = listOf(
        QuickChannel("CNN", listOf("CNN", "CNN US", "CNN USA"), listOf("US"), listOf("news")),
        QuickChannel("CNN International", listOf("CNN International", "CNNI"), listOf("US"), listOf("news")),
        QuickChannel("Fox News", listOf("Fox News", "Fox News Channel", "FNC"), listOf("US"), listOf("news")),
        QuickChannel("MSNBC", listOf("MSNBC", "MSNBC US"), listOf("US"), listOf("news")),
        QuickChannel("CNBC", listOf("CNBC", "CNBC US"), listOf("US"), listOf("news")),
        QuickChannel("ABC News", listOf("ABC News", "ABC News Live"), listOf("US"), listOf("news")),
        QuickChannel("CBS News", listOf("CBS News", "CBS News US"), listOf("US"), listOf("news")),
        QuickChannel("NBC News", listOf("NBC News", "NBC News Now"), listOf("US"), listOf("news")),
        QuickChannel("BBC World News", listOf("BBC World News", "BBC World"), listOf("US", "UK"), listOf("news")),
        QuickChannel("Bloomberg TV", listOf("Bloomberg TV", "Bloomberg Television"), listOf("US"), listOf("news")),
        QuickChannel("NewsNation", listOf("NewsNation", "WGN America"), listOf("US"), listOf("news")),
        QuickChannel("C-SPAN", listOf("C-SPAN", "CSPAN"), listOf("US"), listOf("news")),
        QuickChannel("C-SPAN 2", listOf("C-SPAN 2", "CSPAN 2"), listOf("US"), listOf("news")),
        QuickChannel("PBS", listOf("PBS", "PBS US"), listOf("US"), listOf("news")),
        QuickChannel("The Weather Channel", listOf("The Weather Channel", "Weather Channel", "TWC"), listOf("US"), listOf("news")),
        QuickChannel("Al Jazeera English", listOf("Al Jazeera English", "Al Jazeera"), listOf("US", "UK", "CA"), listOf("news")),
        QuickChannel("France 24 English", listOf("France 24 English", "France 24"), listOf("US", "UK", "CA"), listOf("news")),
        QuickChannel("DW News", listOf("DW News", "Deutsche Welle", "DW"), listOf("US", "UK", "CA"), listOf("news")),
        QuickChannel("BBC News", listOf("BBC News", "BBC News UK", "BBC News Channel"), listOf("UK"), listOf("news")),
        QuickChannel("Sky News", listOf("Sky News", "Sky News UK"), listOf("UK"), listOf("news")),
        QuickChannel("ITV News", listOf("ITV News", "ITV"), listOf("UK"), listOf("news")),
        QuickChannel("Channel 4 News", listOf("Channel 4 News", "Channel 4"), listOf("UK"), listOf("news")),
        QuickChannel("GB News", listOf("GB News"), listOf("UK"), listOf("news")),
        QuickChannel("CBC News", listOf("CBC News", "CBC News Network", "CBC"), listOf("CA"), listOf("news")),
        QuickChannel("CTV News", listOf("CTV News", "CTV News Channel", "CTV"), listOf("CA"), listOf("news")),
        QuickChannel("Global News", listOf("Global News", "Global"), listOf("CA"), listOf("news")),
        QuickChannel("CP24", listOf("CP24"), listOf("CA"), listOf("news")),
        QuickChannel("ESPN", listOf("ESPN", "ESPN US"), listOf("US"), listOf("sports")),
        QuickChannel("ESPN 2", listOf("ESPN 2", "ESPN2"), listOf("US"), listOf("sports")),
        QuickChannel("ESPN News", listOf("ESPN News", "ESPNNews"), listOf("US"), listOf("sports")),
        QuickChannel("ESPN U", listOf("ESPN U", "ESPNU"), listOf("US"), listOf("sports")),
        QuickChannel("Fox Sports 1", listOf("Fox Sports 1", "FS1"), listOf("US"), listOf("sports")),
        QuickChannel("Fox Sports 2", listOf("Fox Sports 2", "FS2"), listOf("US"), listOf("sports")),
        QuickChannel("NBC Sports", listOf("NBC Sports", "NBCSN"), listOf("US"), listOf("sports")),
        QuickChannel("CBS Sports Network", listOf("CBS Sports Network", "CBSSN"), listOf("US"), listOf("sports")),
        QuickChannel("NFL Network", listOf("NFL Network"), listOf("US"), listOf("sports")),
        QuickChannel("NFL RedZone", listOf("NFL RedZone", "NFL Red Zone"), listOf("US"), listOf("sports")),
        QuickChannel("NBA TV", listOf("NBA TV", "NBA TV US"), listOf("US"), listOf("sports")),
        QuickChannel("MLB Network", listOf("MLB Network"), listOf("US"), listOf("sports")),
        QuickChannel("NHL Network", listOf("NHL Network"), listOf("US"), listOf("sports")),
        QuickChannel("Golf Channel", listOf("Golf Channel"), listOf("US"), listOf("sports")),
        QuickChannel("Tennis Channel", listOf("Tennis Channel"), listOf("US"), listOf("sports")),
        QuickChannel("ESPN Deportes", listOf("ESPN Deportes"), listOf("US"), listOf("sports")),
        QuickChannel("Fox Deportes", listOf("Fox Deportes"), listOf("US"), listOf("sports")),
        QuickChannel("SEC Network", listOf("SEC Network"), listOf("US"), listOf("sports")),
        QuickChannel("ACC Network", listOf("ACC Network"), listOf("US"), listOf("sports")),
        QuickChannel("Big Ten Network", listOf("Big Ten Network", "BTN"), listOf("US"), listOf("sports")),
        QuickChannel("Olympic Channel", listOf("Olympic Channel"), listOf("US"), listOf("sports")),
        QuickChannel("Sky Sports Main Event", listOf("Sky Sports Main Event", "Sky Sports Main"), listOf("UK"), listOf("sports")),
        QuickChannel("Sky Sports Premier League", listOf("Sky Sports Premier League", "Sky Sports PL"), listOf("UK"), listOf("sports")),
        QuickChannel("Sky Sports Football", listOf("Sky Sports Football"), listOf("UK"), listOf("sports")),
        QuickChannel("Sky Sports Cricket", listOf("Sky Sports Cricket"), listOf("UK"), listOf("sports")),
        QuickChannel("Sky Sports Golf", listOf("Sky Sports Golf"), listOf("UK"), listOf("sports")),
        QuickChannel("Sky Sports F1", listOf("Sky Sports F1", "Sky Sports Formula 1"), listOf("UK"), listOf("sports")),
        QuickChannel("Sky Sports Arena", listOf("Sky Sports Arena"), listOf("UK"), listOf("sports")),
        QuickChannel("Sky Sports News", listOf("Sky Sports News"), listOf("UK"), listOf("sports")),
        QuickChannel("Sky Sports Racing", listOf("Sky Sports Racing"), listOf("UK"), listOf("sports")),
        QuickChannel("TNT Sports 1", listOf("TNT Sports 1", "BT Sport 1"), listOf("UK"), listOf("sports")),
        QuickChannel("TNT Sports 2", listOf("TNT Sports 2", "BT Sport 2"), listOf("UK"), listOf("sports")),
        QuickChannel("TNT Sports 3", listOf("TNT Sports 3", "BT Sport 3"), listOf("UK"), listOf("sports")),
        QuickChannel("TNT Sports 4", listOf("TNT Sports 4", "BT Sport ESPN"), listOf("UK"), listOf("sports")),
        QuickChannel("DAZN 1 UK", listOf("DAZN 1 UK", "DAZN 1"), listOf("UK"), listOf("sports")),
        QuickChannel("DAZN 2 UK", listOf("DAZN 2 UK", "DAZN 2"), listOf("UK"), listOf("sports")),
        QuickChannel("TSN 1", listOf("TSN 1", "TSN1"), listOf("CA"), listOf("sports")),
        QuickChannel("TSN 2", listOf("TSN 2", "TSN2"), listOf("CA"), listOf("sports")),
        QuickChannel("TSN 3", listOf("TSN 3", "TSN3"), listOf("CA"), listOf("sports")),
        QuickChannel("TSN 4", listOf("TSN 4", "TSN4"), listOf("CA"), listOf("sports")),
        QuickChannel("TSN 5", listOf("TSN 5", "TSN5"), listOf("CA"), listOf("sports")),
        QuickChannel("Sportsnet", listOf("Sportsnet", "Sportsnet Canada"), listOf("CA"), listOf("sports")),
        QuickChannel("Sportsnet One", listOf("Sportsnet One", "Sportsnet 1"), listOf("CA"), listOf("sports")),
        QuickChannel("Sportsnet 360", listOf("Sportsnet 360"), listOf("CA"), listOf("sports")),
        QuickChannel("RDS", listOf("RDS", "Reseau des Sports"), listOf("CA"), listOf("sports")),
        QuickChannel("RDS 2", listOf("RDS 2", "RDS2"), listOf("CA"), listOf("sports")),
        QuickChannel("CBC Sports", listOf("CBC Sports"), listOf("CA"), listOf("sports")),
        QuickChannel("DAZN 1", listOf("DAZN 1"), listOf("US", "UK", "CA"), listOf("sports")),
        QuickChannel("DAZN 2", listOf("DAZN 2"), listOf("US", "UK", "CA"), listOf("sports")),
        QuickChannel("Eurosport 1", listOf("Eurosport 1"), listOf("UK"), listOf("sports")),
        QuickChannel("Eurosport 2", listOf("Eurosport 2"), listOf("UK"), listOf("sports")),
        QuickChannel("beIN Sports", listOf("beIN Sports", "beIN"), listOf("US", "UK", "CA"), listOf("sports")),
        QuickChannel("beIN Sports 2", listOf("beIN Sports 2", "beIN 2"), listOf("US", "UK", "CA"), listOf("sports")),
        QuickChannel("Sport TV 1", listOf("Sport TV 1"), listOf("US", "UK", "CA"), listOf("sports")),
        QuickChannel("Sport TV 2", listOf("Sport TV 2"), listOf("US", "UK", "CA"), listOf("sports")),
        QuickChannel("HBO", listOf("HBO", "HBO US", "HBO East"), listOf("US"), listOf("premium")),
        QuickChannel("HBO 2", listOf("HBO 2", "HBO2"), listOf("US"), listOf("premium")),
        QuickChannel("HBO Signature", listOf("HBO Signature"), listOf("US"), listOf("premium")),
        QuickChannel("HBO Family", listOf("HBO Family"), listOf("US"), listOf("premium")),
        QuickChannel("HBO Comedy", listOf("HBO Comedy"), listOf("US"), listOf("premium")),
        QuickChannel("HBO Latino", listOf("HBO Latino"), listOf("US"), listOf("premium")),
        QuickChannel("Showtime", listOf("Showtime", "Showtime US", "Showtime East"), listOf("US"), listOf("premium")),
        QuickChannel("Showtime 2", listOf("Showtime 2", "Showtime Too"), listOf("US"), listOf("premium")),
        QuickChannel("Starz", listOf("Starz", "Starz US", "Starz East"), listOf("US"), listOf("premium")),
        QuickChannel("Starz Edge", listOf("Starz Edge"), listOf("US"), listOf("premium")),
        QuickChannel("Starz Comedy", listOf("Starz Comedy"), listOf("US"), listOf("premium")),
        QuickChannel("Starz Kids & Family", listOf("Starz Kids & Family", "Starz Kids"), listOf("US"), listOf("premium")),
        QuickChannel("Starz Encore", listOf("Starz Encore"), listOf("US"), listOf("premium")),
        QuickChannel("Starz Encore Action", listOf("Starz Encore Action"), listOf("US"), listOf("premium")),
        QuickChannel("Starz Encore Westerns", listOf("Starz Encore Westerns"), listOf("US"), listOf("premium")),
        QuickChannel("Cinemax", listOf("Cinemax"), listOf("US"), listOf("premium")),
        QuickChannel("MoreMax", listOf("MoreMax", "More Max"), listOf("US"), listOf("premium")),
        QuickChannel("MGM+", listOf("MGM+", "MGM Plus", "Epix"), listOf("US"), listOf("premium")),
        QuickChannel("TMC", listOf("TMC", "The Movie Channel"), listOf("US"), listOf("premium")),
        QuickChannel("Sky Cinema Premiere", listOf("Sky Cinema Premiere"), listOf("UK"), listOf("premium")),
        QuickChannel("Sky Cinema Greats", listOf("Sky Cinema Greats"), listOf("UK"), listOf("premium")),
        QuickChannel("Sky Cinema Family", listOf("Sky Cinema Family"), listOf("UK"), listOf("premium")),
        QuickChannel("Sky Cinema Action", listOf("Sky Cinema Action"), listOf("UK"), listOf("premium")),
        QuickChannel("Sky Cinema Comedy", listOf("Sky Cinema Comedy"), listOf("UK"), listOf("premium")),
        QuickChannel("Sky Cinema Hits", listOf("Sky Cinema Hits"), listOf("UK"), listOf("premium")),
        QuickChannel("BBC One", listOf("BBC One"), listOf("UK"), listOf("premium")),
        QuickChannel("BBC Two", listOf("BBC Two"), listOf("UK"), listOf("premium")),
        QuickChannel("ITV1", listOf("ITV1", "ITV 1", "ITV"), listOf("UK"), listOf("premium")),
        QuickChannel("ITV2", listOf("ITV2", "ITV 2"), listOf("UK"), listOf("premium")),
        QuickChannel("ITV3", listOf("ITV3", "ITV 3"), listOf("UK"), listOf("premium")),
        QuickChannel("ITV4", listOf("ITV4", "ITV 4"), listOf("UK"), listOf("premium")),
        QuickChannel("Channel 4", listOf("Channel 4"), listOf("UK"), listOf("premium")),
        QuickChannel("Channel 5", listOf("Channel 5"), listOf("UK"), listOf("premium")),
        QuickChannel("CBC", listOf("CBC", "CBC Television"), listOf("CA"), listOf("premium")),
        QuickChannel("CTV", listOf("CTV", "CTV Television"), listOf("CA"), listOf("premium")),
        QuickChannel("CTV 2", listOf("CTV 2", "CTV2"), listOf("CA"), listOf("premium")),
        QuickChannel("Global TV", listOf("Global TV", "Global"), listOf("CA"), listOf("premium")),
        QuickChannel("Citytv", listOf("Citytv"), listOf("CA"), listOf("premium")),
        QuickChannel("Crave", listOf("Crave", "Crave TV"), listOf("CA"), listOf("premium")),
        QuickChannel("Crave 1", listOf("Crave 1"), listOf("CA"), listOf("premium")),
        QuickChannel("Crave 2", listOf("Crave 2"), listOf("CA"), listOf("premium")),
        QuickChannel("Crave 3", listOf("Crave 3"), listOf("CA"), listOf("premium")),
        QuickChannel("HBO Canada", listOf("HBO Canada"), listOf("CA"), listOf("premium")),
        QuickChannel("Super Channel", listOf("Super Channel"), listOf("CA"), listOf("premium")),
        QuickChannel("ABC", listOf("ABC", "ABC US"), listOf("US"), listOf("premium")),
        QuickChannel("CBS", listOf("CBS", "CBS US"), listOf("US"), listOf("premium")),
        QuickChannel("NBC", listOf("NBC", "NBC US"), listOf("US"), listOf("premium")),
        QuickChannel("FOX", listOf("FOX", "FOX US"), listOf("US"), listOf("premium")),
        QuickChannel("The CW", listOf("The CW", "CW"), listOf("US"), listOf("premium")),
        QuickChannel("AMC", listOf("AMC"), listOf("US"), listOf("premium")),
        QuickChannel("USA Network", listOf("USA Network", "USA"), listOf("US"), listOf("premium")),
        QuickChannel("TNT", listOf("TNT", "TNT US"), listOf("US"), listOf("premium")),
        QuickChannel("TBS", listOf("TBS", "TBS US"), listOf("US"), listOf("premium")),
        QuickChannel("FX", listOf("FX", "FX US"), listOf("US"), listOf("premium")),
        QuickChannel("FXX", listOf("FXX"), listOf("US"), listOf("premium")),
        QuickChannel("Comedy Central", listOf("Comedy Central"), listOf("US"), listOf("premium")),
        QuickChannel("History Channel", listOf("History Channel", "History"), listOf("US"), listOf("premium")),
        QuickChannel("Discovery Channel", listOf("Discovery Channel", "Discovery"), listOf("US"), listOf("premium")),
        QuickChannel("National Geographic", listOf("National Geographic", "Nat Geo"), listOf("US"), listOf("premium")),
        QuickChannel("Animal Planet", listOf("Animal Planet"), listOf("US"), listOf("premium")),
        QuickChannel("Food Network", listOf("Food Network"), listOf("US"), listOf("premium")),
        QuickChannel("HGTV", listOf("HGTV"), listOf("US"), listOf("premium")),
        QuickChannel("Travel Channel", listOf("Travel Channel"), listOf("US"), listOf("premium")),
        QuickChannel("Bravo", listOf("Bravo", "Bravo US"), listOf("US"), listOf("premium")),
        QuickChannel("SyFy", listOf("SyFy", "Syfy", "Sci-Fi"), listOf("US"), listOf("premium")),
        QuickChannel("MTV", listOf("MTV", "MTV US"), listOf("US"), listOf("premium")),
        QuickChannel("VH1", listOf("VH1"), listOf("US"), listOf("premium")),
        QuickChannel("BET", listOf("BET", "Black Entertainment TV"), listOf("US"), listOf("premium")),
        QuickChannel("TLC", listOf("TLC"), listOf("US"), listOf("premium")),
        QuickChannel("A&E", listOf("A&E", "A and E"), listOf("US"), listOf("premium")),
        QuickChannel("Lifetime", listOf("Lifetime"), listOf("US"), listOf("premium")),
        QuickChannel("E!", listOf("E!", "E Entertainment"), listOf("US"), listOf("premium")),
        QuickChannel("Paramount Network", listOf("Paramount Network", "Paramount", "Spike"), listOf("US"), listOf("premium")),
        QuickChannel("Freeform", listOf("Freeform", "ABC Family"), listOf("US"), listOf("premium")),
        QuickChannel("Nickelodeon", listOf("Nickelodeon", "Nick"), listOf("US"), listOf("premium")),
        QuickChannel("Cartoon Network", listOf("Cartoon Network", "CN"), listOf("US"), listOf("premium")),
        QuickChannel("Disney Channel", listOf("Disney Channel", "Disney"), listOf("US"), listOf("premium")),
        QuickChannel("Disney XD", listOf("Disney XD"), listOf("US"), listOf("premium")),
        QuickChannel("Disney Junior", listOf("Disney Junior"), listOf("US"), listOf("premium")),
        QuickChannel("Adult Swim", listOf("Adult Swim"), listOf("US"), listOf("premium")),
        QuickChannel("YES Network", listOf("YES Network"), listOf("US"), listOf("sports")),
        QuickChannel("NESN", listOf("NESN"), listOf("US"), listOf("sports")),
        QuickChannel("MASN", listOf("MASN"), listOf("US"), listOf("sports")),
        QuickChannel("MSG Network", listOf("MSG Network", "MSG"), listOf("US"), listOf("sports")),
        QuickChannel("Marquee Sports Network", listOf("Marquee Sports Network"), listOf("US"), listOf("sports")),

        // ── San Francisco Bay Area Local ────────────────────────────────────
        QuickChannel("KTVU Fox 2", listOf("KTVU", "KTVU Fox 2", "FOX 2 KTVU", "KTVU San Francisco"), listOf("US", "bay-area"), listOf("regional", "news")),
        QuickChannel("KPIX CBS 5", listOf("KPIX", "KPIX CBS 5", "CBS 5 KPIX", "CBS Bay Area"), listOf("US", "bay-area"), listOf("regional", "news")),
        QuickChannel("KGO ABC 7", listOf("KGO", "KGO ABC 7", "ABC 7 KGO", "ABC7 Bay Area"), listOf("US", "bay-area"), listOf("regional", "news")),
        QuickChannel("KRON 4", listOf("KRON", "KRON 4", "KRON4", "KRON News"), listOf("US", "bay-area"), listOf("regional", "news")),
        QuickChannel("KNTV NBC Bay Area", listOf("KNTV", "KNTV NBC 11", "NBC Bay Area", "NBC 11", "KNTV Bay Area"), listOf("US", "bay-area"), listOf("regional", "news")),
        QuickChannel("KQED 9", listOf("KQED", "KQED 9", "KQED PBS", "PBS KQED"), listOf("US", "bay-area"), listOf("regional", "news")),
        QuickChannel("KBCW CW 44", listOf("KBCW", "KBCW CW 44", "CW 44", "CW Bay Area"), listOf("US", "bay-area"), listOf("regional")),
        QuickChannel("KICU MyNetwork 36", listOf("KICU", "KICU 36", "MyNetwork 36", "KICU Bay Area"), listOf("US", "bay-area"), listOf("regional")),
        QuickChannel("KDTV Univision 14", listOf("KDTV", "KDTV Univision 14", "Univision 14", "Univision Bay Area"), listOf("US", "bay-area"), listOf("regional")),
        QuickChannel("KTSF 26", listOf("KTSF", "KTSF 26", "KTSF Bay Area"), listOf("US", "bay-area"), listOf("regional")),
        QuickChannel("KTVU Fox 2 Plus", listOf("KTVU Plus", "KTVU Fox 2 Plus", "KTVU+"), listOf("US", "bay-area"), listOf("regional")),
        QuickChannel("NBC Bay Area News", listOf("NBC Bay Area News", "NBCBA News", "NBC Bay Area Nonstop"), listOf("US", "bay-area"), listOf("regional", "news")),
    )
}
