package com.nuvio.app.features.hub

/**
 * Immutable "Staff Picks" hub — always shown first and never editable/deletable.
 * Each entry is a YouTube channel rendered as its own video rail.
 */
object VidNutzStaffPicks {

    private fun channel(name: String): VidNutzSub =
        VidNutzSub(
            id = name.lowercase().replace(Regex("[^a-z0-9]+"), "-").trim('-'),
            name = name,
            count = 0,
            queries = listOf(name),
        )

    val hub: VidNutzHub = VidNutzHub(
        id = STAFF_PICKS_HUB_ID,
        displayName = "Staff Picks",
        subs = listOf(
            channel("Poetik Flakko"),
            channel("DeVory Darkins"),
            channel("Piers Morgan Uncensored"),
            channel("Hannibal Is Hungry"),
            channel("World Of Fuush"),
            channel("Amala Ekpunobi"),
            channel("Brandon Lehman"),
            channel("Stephen A. Smith"),
            channel("LATRYGUY"),
            channel("Matt Wolfe"),
            channel("SJohnsonVoiceOvers"),
            channel("MattVidPro"),
            channel("Omma"),
            channel("newtech"),
            channel("KINGDOM REACTS"),
            channel("The Trey King Show"),
            channel("Lil Poudii"),
            channel("Cocoa Butter"),
            channel("The Next New Thing"),
            channel("Helena Liu"),
            channel("MrLboyd Reacts"),
            channel("Her Patriot Voice"),
            channel("TheAIGRID"),
            channel("ManuAGI - AutoGPT Tutorials"),
            channel("HYPE+"),
            channel("The Perseverance"),
            channel("The Officer Tatum"),
            channel("AI Search"),
            channel("Alex Finn"),
            channel("Julian Goldie SEO"),
            channel("UFC"),
            channel("Duncan Rogoff | Learn Claude Code"),
            channel("URBAN POLITICIANS TV"),
            channel("Complex"),
            channel("Electrical MD"),
            channel("T Pain"),
            channel("Roland S. Martin"),
            channel("Yaad Life's Good"),
            channel("Wes Roth"),
            channel("Matthew Berman"),
            channel("NOT ANOTHER COOKING SHOW"),
            channel("Millionaire Morning Show"),
            channel("Jubilee"),
            channel("All Def"),
            channel("Mr.ChimeTime"),
            channel("The Saint"),
            channel("NPR Music"),
            channel("Rob The AI Guy"),
            channel("Anton Daniels"),
            channel("Eddie Griffin"),
            channel("Hayls World"),
            channel("StarTalk"),
            channel("Industry Secrets"),
            channel("djvlad"),
            channel("Danny Kim"),
            channel("Kimmy's Kreations"),
            channel("Speakeasy"),
            channel("Matthew Lesko"),
            channel("Smoke N' Scan"),
            channel("The Diary Of A CEO"),
            channel("WorldofAI"),
            channel("The Conscious Lee"),
            channel("The Trading Parrot"),
            channel("ESPN"),
            channel("4biddenknowledge Podcast Network"),
            channel("Derrick Grace II"),
            channel("The Majority Report w/ Sam Seder"),
            channel("Hip Hop News Uncensored"),
            channel("Trilogy Media"),
            channel("MustangMedic"),
            channel("AIQUEST"),
            channel("Tech-Practice"),
            channel("Discover Crypto"),
            channel("BULLRUNNERS"),
            channel("Flossy Carter"),
            channel("NFL"),
            channel("Koh"),
            channel("allthingsbbq"),
            channel("African Diaspora News Channel"),
            channel("Kevin Samuels"),
            channel("HOT 97"),
            channel("The Angryman"),
            channel("Trading Fraternity"),
            channel("The Art Of Dialogue"),
            channel("Mother Jones"),
            channel("TheFigCo"),
            channel("Timeless Barbers"),
            channel("Myles G Investments"),
            channel("Mark Stache"),
            channel("G Rich"),
            channel("Tyrin Barney"),
            channel("FUNarios"),
            channel("Kenan Grace"),
            channel("ALTER"),
            channel("Mark J Kohler"),
            channel("Shane Hummus"),
            channel("The Ariel Helwani Show"),
            channel("STREETBEEFS"),
            channel("Candace Owens"),
            channel("Bounty Tank"),
            channel("Everything Kevo"),
            channel("Dennis Kirk, Inc."),
            channel("REVOLT"),
            channel("Detour Shirts"),
            channel("McQueen On Air"),
            channel("Gary Owen"),
            channel("Stalekracker Official"),
            channel("Demons Row"),
            channel("Zubair Trabzada | AI Workshop"),
            channel("FLAGRANT CLIPS"),
            channel("The Kwak Brothers"),
            channel("The Andrew Schulz"),
            channel("The B Hayes Show"),
            channel("Joe Budden TV"),
            channel("BETNetworks"),
            channel("WORLDSTARHIPHOP"),
            channel("Nate Herk | AI Automation"),
            channel("Custom Offsets"),
            channel("AshandtheChaos"),
            channel("The AI Daily Brief"),
            channel("Crank Lucas"),
            channel("Shout! Studios"),
            channel("The 85 South Comedy Show"),
            channel("No Jumper"),
            channel("The Fumble"),
            channel("9CHINO2CHING5"),
            channel("Absolute History"),
            channel("ScottieDTV"),
            channel("Sabby Sabs"),
            channel("corbin"),
            channel("Stock Moe"),
            channel("Hes Kicks"),
            channel("Jay Williams Let's Live Life"),
            channel("Social Proof"),
            channel("Smokin' & Grillin with AB"),
            channel("Daym Drops"),
            channel("Mighty Car Mods"),
            channel("All Your Tech AI"),
            channel("LNSPLTBLVD"),
            channel("Paul Barron Network"),
            channel("Full Value Dan"),
            channel("Android Developers"),
            channel("Fireship"),
            channel("The Dawgfatha's BBQ"),
            channel("Killer Mike"),
            channel("Netflix Is A Joke"),
            channel("Ross Cameron - Warrior Trading"),
            channel("Prompt Engineering"),
            channel("Futurepedia"),
            channel("Real Crime"),
            channel("Be The Boss Of Your Motorcycle!"),
            channel("CoinDesk"),
            channel("60MvTv"),
            channel("Coin Bureau"),
            channel("MrBallen"),
            channel("Holley"),
            channel("The Dr. Phil Podcast"),
            channel("The Daily Show"),
            channel("Big Brandoh"),
            channel("FHO ATLANTA, GA."),
            channel("AXS TV"),
            channel("Mecum Auctions"),
            channel("Nice Kicks"),
            channel("Sav Says"),
            channel("GabeTrades"),
            channel("Ed Bassmaster"),
            channel("VICE News"),
            channel("The Clever Millionaire"),
            channel("Breakfast Club Power 105.1 FM"),
            channel("STRELKA STREET FIGHTS"),
            channel("UNINTERRUPTED"),
            channel("FLAGRANT"),
            channel("The Bleu Channel"),
        ),
    )
}
