package com.nuvio.app.features.player

import androidx.compose.ui.Modifier
import com.nuvio.app.features.sports.YoutubeQuality

internal data class PlayerScreenArgs(
    val profileId: Int,
    val title: String,
    val sourceUrl: String,
    val sourceAudioUrl: String?,
    val qualities: List<YoutubeQuality> = emptyList(),
    val sourceHeaders: Map<String, String>,
    val sourceResponseHeaders: Map<String, String>,
    val streamType: String?,
    val providerName: String,
    val streamTitle: String,
    val streamSubtitle: String?,
    val initialBingeGroup: String?,
    val pauseDescription: String?,
    val onBack: () -> Unit,
    val onOpenInExternalPlayer: ((ExternalPlayerPlaybackRequest) -> Unit)?,
    val onOpenExternalUrl: ((String) -> Unit)?,
    val modifier: Modifier,
    val logo: String?,
    val poster: String?,
    val background: String?,
    val seasonNumber: Int?,
    val episodeNumber: Int?,
    val episodeTitle: String?,
    val episodeThumbnail: String?,
    val contentType: String?,
    val videoId: String?,
    val parentMetaId: String,
    val parentMetaType: String,
    val providerAddonId: String?,
    val externalSubtitles: List<com.nuvio.app.features.streams.StreamSubtitle> = emptyList(),
    val torrentInfoHash: String?,
    val torrentFileIdx: Int?,
    val torrentFilename: String?,
    val torrentTrackers: List<String>,
    val initialPositionMs: Long,
    val initialProgressFraction: Float?,
    val contentLanguage: String? = null,
    val launchId: Long = 0L,
    val onSwitchIptvChannel: ((Long) -> Unit)? = null,
    val iptvChannelIds: List<String>? = null,
    val iptvChannelNames: List<String>? = null,
    val iptvChannelUrls: List<String>? = null,
    val iptvChannelLogos: List<String>? = null,
    val iptvCurrentChannelIndex: Int = 0,
    val iptvFavoriteIds: Set<String>? = null,
    val onToggleIptvFavorite: ((String) -> Unit)? = null,
    val iptvHistoryNames: List<String>? = null,
    val iptvHistoryUrls: List<String>? = null,
    val iptvHistoryLogos: List<String>? = null,
    val iptvHistoryIds: List<String>? = null,
    val autoPlayQueueUrls: List<String> = emptyList(),
    val autoPlayQueueTitles: List<String> = emptyList(),
    val autoPlayQueueIndex: Int = 0,
    val onAutoPlayNext: ((Long) -> Unit)? = null,
)
